### ISSUE TITLE
Styling du body inefficace 

### ISSUE THREAD

**Issue by ysitbon** [TonTonKam/porteFolioJs#1]
https://github.com/TonTonKam/porteFolioJs/blob/1d2f87bbee23e837fe660df835c08aad65476a62/js/script.js#L2-L4

à supprimer complètement et à placer dans ta feuille de style:

```css
body {
  display: flex; 
  font-size: 18px;
} 
```
