### ISSUE TITLE
Styling de la nav inefficace

### ISSUE THREAD

**Issue by ysitbon** [TonTonKam/porteFolioJs#2]
https://github.com/TonTonKam/porteFolioJs/blob/1d2f87bbee23e837fe660df835c08aad65476a62/js/script.js#L14-L15

à supprimer complétement et à placer dans ta feuille de style:

```css
nav {
  flex: 2; 
} 
```
