### ISSUE TITLE
Styling de l'ul inefficace

### ISSUE THREAD

**Issue by ysaskia** [TonTonKam/porteFolioJs#3]
https://github.com/TonTonKam/porteFolioJs/blob/1d2f87bbee23e837fe660df835c08aad65476a62/js/script.js#L18-L25

à supprimer complètement et à placer dans ta feuille de style.

```css
ul {
  display: flex;
  flex-direction: column;
  margin: 0;
  padding: 0;
}
```
